<?PHP
/**
 *  @copyright SimpleCRM http://www.simplecrm.com.sg
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
 * along with this program; if not, see http://www.gnu.org/licenses
 * or write to the Free Software Foundation,Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA 02110-1301  USA
 *
 * @author SimpleCRM <info@simplecrm.com.sg>
 */


/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN scrm_Partner_Contacts
 */

require_once('include/SugarObjects/templates/person/Person.php');

class scrm_Partner_Contacts_sugar extends Person {
	var $new_schema = true;
	var $module_dir = 'scrm_Partner_Contacts';
	var $object_name = 'scrm_Partner_Contacts';
	var $table_name = 'scrm_partner_contacts';
	var $importable = true;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $salutation;
		var $first_name;
		var $last_name;
		var $full_name;
		var $title;
		var $photo;
		var $department;
		var $do_not_call;
		var $phone_home;
		var $email;
		var $phone_mobile;
		var $phone_work;
		var $phone_other;
		var $phone_fax;
		var $email1;
		var $email2;
		var $invalid_email;
		var $email_opt_out;
		var $primary_address_street;
		var $primary_address_street_2;
		var $primary_address_street_3;
		var $primary_address_city;
		var $primary_address_state;
		var $primary_address_postalcode;
		var $primary_address_country;
		var $alt_address_street;
		var $alt_address_street_2;
		var $alt_address_street_3;
		var $alt_address_city;
		var $alt_address_state;
		var $alt_address_postalcode;
		var $alt_address_country;
		var $assistant;
		var $assistant_phone;
		var $email_addresses_primary;
		var $email_addresses;
		var $email_addresses_non_primary;
		function scrm_Partner_Contacts_sugar(){	
		parent::Person();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>
